version: '2'
services:
  nginx:
      build: ~/Work/docker/nginx
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ~/Work:/opt/web
        - ~/Work/log:/opt/log
      restart: always
      links:
        - php
  php:
      build: ~/Work/docker/php
      container_name: php
      ports:
        - "9000"
      volumes:
        - ~/Work:/opt/web
      restart: always
      extra_hosts:
        - "api.im.com:127.0.0.1"
      links:
        - redis
        - mysql
  mysql:
      build: ~/Work/docker/mysql/file
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - ~/Work/data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      restart: always
  redis:
      build: ~/Work/docker/redis/file
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - ~/Work/data/redis:/data
      restart: always

